### ISSUE TITLE
Run `bundle install` before a `pod install` if there is a Gemfile in a project

### ISSUE THREAD

**Issue by orta** [bitrise-io/steps-cocoapods-and-repository-validator#5]
Running against: [artsy/Aerodramus](https://github.com/artsy/Aerodramus)

```
-> $ bash /Users/vagrant/stepdir/run_pod_install.sh

### Searching for podfiles and installing the found ones

 (i) Podfile found at: ./Example/Podfile
 (i) Podfile directory: ./Example

 ===> Pod install: ./Example/Podfile
--- Config:
{:podfile_path=>"Podfile"}
-----------

-> Fixing sources in Podfile

 (i) podfile_abs_path: /Users/vagrant/git/Example/Podfile
source: ["source", "'https://github.com/CocoaPods/Specs.git'"]
expected_uri_part: https://github.com/CocoaPods/Specs.git
 * [no-fix] uri (https://github.com/CocoaPods/Specs.git) should be handled by pod install, no fix required.

-> Finished with source fixes.
  Preparing
[!] Your Podfile requires that the plugin `cocoapods-keys` be installed. Please install it and try installation again.
```

The problem at it's core is that this isn't aware of CocoaPods plugins. There are two ways in which someone is using them, gemfiles and the global gems installation. In my case there is a Gemfile, so I would expect a `bundle install` first, then a `bundle exec pod install`. 

But if you don't use a gem file, then you can look in the Podfile for `plugin 'cocoapods-keys', ` - you have to have the Gem installation name as the plugin name, so you can rely on looking inside the string after plugin in order to ensure it's installed.

**Comment by viktorbenei** [comment]
Thanks for reporting @orta ! This step is quite old now and is part of our ongoing revision to make it cleaner & less bloated.

The best alternative before we get here to fix this issue is to simply use a script step and do anything required for your project setup, something like this:

```
set -v
set -e
bundle install
pod install
```
